# Generated by Django 5.2.7 on 2026-05-18 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('realizadoem', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentoAdocao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
                ('enviadoem', models.DateTimeField(auto_now_add=True)),
                ('arquivo', models.FileField(upload_to='adocao/documentos/')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessoAdocao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criadaem', models.DateTimeField(auto_now_add=True)),
                ('atualizadaem', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('EM_ANALISE', 'Em Análise'), ('APROVADA', 'Aprovada'), ('REPROVADA', 'Reprovada')], default='EM_ANALISE', max_length=20)),
            ],
        ),
    ]
