# Generated by Django 5.2.7 on 2026-05-18 23:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adocao', '0001_initial'),
        ('animais', '0003_alter_animal_options_alter_raca_options_and_more'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_autor', to='usuarios.usuario'),
        ),
        migrations.AddField(
            model_name='processoadocao',
            name='adotante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processos_adocao_adotante', to='usuarios.usuario'),
        ),
        migrations.AddField(
            model_name='processoadocao',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processos_adocao', to='animais.animal'),
        ),
        migrations.AddField(
            model_name='processoadocao',
            name='avaliador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processos_adocao_avaliador', to='usuarios.usuario'),
        ),
        migrations.AddField(
            model_name='processoadocao',
            name='comentarios',
            field=models.ManyToManyField(blank=True, related_name='comentarios_usuario', through='adocao.Comentario', to='usuarios.usuario'),
        ),
        migrations.AddField(
            model_name='documentoadocao',
            name='processo_adocao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='adocao.processoadocao'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='processo_adocao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_processo', to='adocao.processoadocao'),
        ),
    ]
