# Generated by Django 6.0.3 on 2026-05-26 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="tipo",
            field=models.CharField(
                choices=[("1", "ADOTANTE"), ("2", "AVALIADOR")], max_length=1
            ),
        ),
    ]
