# Generated by Django 6.0.3 on 2026-06-02 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0002_alter_usuario_tipo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usuario",
            name="tipo",
        ),
    ]
