# Generated by Django 6.0.3 on 2026-05-26 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("animais", "0004_racaordenada_alter_tipoanimal_options"),
        ("usuarios", "0002_alter_usuario_tipo"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comentario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("texto", models.TextField()),
                ("realizado_em", models.DateTimeField(auto_now=True)),
                (
                    "avaliador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="comentarios",
                        to="usuarios.usuario",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProcessoAdocao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("criadaem", models.DateField(auto_now_add=True)),
                ("atualizadaem", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("EM_ANALISE", "Em Análise"),
                            ("APROVADA", "Aprovada"),
                            ("REPROVADA", "Reprovada"),
                        ],
                        default="EM_ANALISE",
                        max_length=10,
                    ),
                ),
                (
                    "adotante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="processos_adocao_adotante",
                        to="usuarios.usuario",
                    ),
                ),
                (
                    "animal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="processos_adocao",
                        to="animais.animal",
                    ),
                ),
                (
                    "avaliador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="processos_adocao_avaliador",
                        to="usuarios.usuario",
                    ),
                ),
                (
                    "comentarios_avaliadores",
                    models.ManyToManyField(
                        related_name="comentarios_avaliadores",
                        through="adocoes.Comentario",
                        to="usuarios.usuario",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Documento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descricao", models.CharField(max_length=100)),
                ("arquivo", models.FileField(upload_to="adocoes/documentos/")),
                ("enviado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "processo_adocao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documentos",
                        to="adocoes.processoadocao",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="comentario",
            name="processo_adocao",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="comentarios",
                to="adocoes.processoadocao",
            ),
        ),
    ]
