# Generated by Django 5.2.7 on 2026-05-06 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Raca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TipoAnimal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data_nascimento', models.DateField()),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1)),
                ('cor', models.CharField(max_length=50)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('raca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animais', to='animais.raca')),
            ],
        ),
        migrations.AddField(
            model_name='raca',
            name='tipo_animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='racas', to='animais.tipoanimal'),
        ),
    ]
