# Generated by Django 5.2.14 on 2026-05-06 20:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("animais", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="animal",
            name="disponivel",
            field=models.BooleanField(default=True, null=True),
        ),
    ]
