# Generated by Django 6.0.3 on 2026-05-21 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animais", "0002_alter_raca_nome"),
    ]

    operations = [
        migrations.AddField(
            model_name="animal",
            name="foto",
            field=models.ImageField(blank=True, upload_to="animais/fotos/"),
        ),
    ]
