# Generated by Django 5.2.7 on 2026-05-18 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animais', '0002_animal_disponivel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animal',
            options={'ordering': ['nome'], 'verbose_name_plural': 'Animais'},
        ),
        migrations.AlterModelOptions(
            name='raca',
            options={'ordering': ['tipo_animal__nome', 'nome'], 'verbose_name_plural': 'Raças'},
        ),
        migrations.AlterModelOptions(
            name='tipoanimal',
            options={'ordering': ['nome'], 'verbose_name_plural': 'Tipos de Animais'},
        ),
        migrations.AddField(
            model_name='animal',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_animais/'),
        ),
    ]
