# Generated by Django 6.0.3 on 2026-05-26 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("animais", "0003_animal_foto"),
    ]

    operations = [
        migrations.CreateModel(
            name="RacaOrdenada",
            fields=[],
            options={
                "ordering": ["nome"],
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("animais.raca",),
        ),
        migrations.AlterModelOptions(
            name="tipoanimal",
            options={"verbose_name_plural": "Tipos de Animais"},
        ),
    ]
