# Generated by Django 6.0.3 on 2026-06-02 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("animais", "0003_alter_animal_options_alter_raca_options_and_more"),
        ("animais", "0004_racaordenada_alter_tipoanimal_options"),
    ]

    operations = []
