# Generated by Django 6.0.3 on 2026-06-02 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animais", "0005_merge_20260602_1220"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tipoanimal",
            options={"ordering": ["nome"], "verbose_name_plural": "Tipos de Animais"},
        ),
        migrations.AlterField(
            model_name="animal",
            name="foto",
            field=models.ImageField(blank=True, null=True, upload_to="fotos_animais/"),
        ),
        migrations.AlterField(
            model_name="raca",
            name="nome",
            field=models.CharField(max_length=50),
        ),
    ]
