# Generated by Django 6.0.3 on 2026-06-23 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("animais", "0006_alter_tipoanimal_options_alter_animal_foto_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tipoanimal",
            options={
                "ordering": ["nome"],
                "permissions": [
                    ("pode_visualizar_tipoanimal", "Pode Visualizar Tipo de Animal")
                ],
                "verbose_name_plural": "Tipos de Animais",
            },
        ),
    ]
