# Generated by Django 6.0.3 on 2026-07-02 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animais", "0007_alter_tipoanimal_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="animal",
            name="foto",
            field=models.ImageField(blank=True, null=True, upload_to="animais/"),
        ),
    ]
